name = "DisjointCliqueCover"
uuid = "f7dc3c69-b0f0-46d7-a66a-b632855ee0cb"
authors = ["Giulio Burgio <giulioburgio@gmail.com>", "Sergio Gómez <sergio.gomez@urv.cat>", "Joan T. Matamalas <jtmatamalas@protonmail.com>"]
version = "0.1.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Combinatorics = "0.7, 1.0"
LightGraphs = "1.0, 1.3"
StatsBase = "0.32, 0.33"
julia = "1.2, 1.6"
